### ISSUE TITLE
Can boundary knots be specified with multiplicities?

### ISSUE THREAD

**Issue by mihaiconstantin** [wenjie2wang/splines2#1]
This may not be the best place to ask this question. I apologize for that.

I would appreciate it if you can help me understand a use case scenario regarding the `boundary_knots`.

Is it possible to define an extended partition (i.e., by specifying some knots with multiplicities)? 
I a nutshell, I am interested to see if `splines2` can account for the following scenario (https://rpubs.com/deleeuw/268327):

![Splines Extended Parition](https://user-images.githubusercontent.com/20051042/88048328-6bd3fb00-cb53-11ea-9cee-64644bc35cfa.png)

Looking at the code of `clean_knots()` in class `SplineBase`, I believe this is not possible since only unique elements are retained after executing `arma::unique(boundary_knots)`.

https://github.com/wenjie2wang/splines2/blob/1de1d904bc6c48fdaa6a7e8806e3e3d8ea6206c2/inst/include/splines2Armadillo/SplineBase.h#L81-L89

Is there a workaround for this, or am I missing something?

P.S. Thanks for this great package! :)

**Comment by mihaiconstantin** [comment]
Hi @wenjie2wang,

Thank you very much for the prompt and detailed response!
This not only answers my question but also helps me clarify a couple of things. 
I hope it will also be helpful to others as well.

Do you want me to close the 'issue'?

**Comment by wenjie2wang** [comment]
My pleasure.  Glad to hear that it helps.  I can close this issue.
