### ISSUE TITLE
installation fails on a linux server with R-4.0.3

### ISSUE THREAD

**Issue by mortamini** [wenjie2wang/splines2#14]
I want to install splines2 on a linux server using the source file and the following command:

R CMD INSTALL -l /home/mort_amini/  --no-lock splines2_0.4.5.tar.gz

(I have tried without the option --no-lock and I have received an error about failure of locking folder before)

and I receive the following output:

* installing *source* package â€کsplines2â€™ ...
** package â€کsplines2â€™ successfully unpacked and MD5 sums checked
staged installation is only possible with locking
** using non-staged installation
** libs
In file included from ../inst/include/splines2Armadillo/BSpline.h:25:0,
                 from ../inst/include/splines2Armadillo.h:21,
                 from BSpline_export.cpp:21:
../inst/include/splines2Armadillo/SplineBase.h:455:29: warning: inline function â€کvirtual splines2::rmat splines2::SplineBase::integral(bool)â€™ used but never defined
         inline virtual rmat integral(
                             ^
In file included from ../inst/include/splines2Armadillo/BSpline.h:25:0,
                 from ../inst/include/splines2Armadillo.h:21,
                 from BernsteinPoly_export.cpp:21:
../inst/include/splines2Armadillo/SplineBase.h:455:29: warning: inline function â€کvirtual splines2::rmat splines2::SplineBase::integral(bool)â€™ used but never defined
         inline virtual rmat integral(
                             ^
In file included from ../inst/include/splines2Armadillo/BSpline.h:25:0,
                 from ../inst/include/splines2Armadillo.h:21,
                 from CSpline_export.cpp:21:
../inst/include/splines2Armadillo/SplineBase.h:455:29: warning: inline function â€کvirtual splines2::rmat splines2::SplineBase::integral(bool)â€™ used but never defined
         inline virtual rmat integral(
                             ^
In file included from ../inst/include/splines2Armadillo/BSpline.h:25:0,
                 from ../inst/include/splines2Armadillo.h:21,
                 from ISpline_export.cpp:21:
../inst/include/splines2Armadillo/SplineBase.h:455:29: warning: inline function â€کvirtual splines2::rmat splines2::SplineBase::integral(bool)â€™ used but never defined
         inline virtual rmat integral(
                             ^
In file included from ../inst/include/splines2Armadillo/BSpline.h:25:0,
                 from ../inst/include/splines2Armadillo.h:21,
                 from MSpline_export.cpp:21:
../inst/include/splines2Armadillo/SplineBase.h:455:29: warning: inline function â€کvirtual splines2::rmat splines2::SplineBase::integral(bool)â€™ used but never defined
         inline virtual rmat integral(
                             ^
In file included from ../inst/include/splines2Armadillo/BSpline.h:25:0,
                 from ../inst/include/splines2Armadillo.h:21,
                 from NaturalSpline_export.cpp:21:
../inst/include/splines2Armadillo/SplineBase.h:455:29: warning: inline function â€کvirtual splines2::rmat splines2::SplineBase::integral(bool)â€™ used but never defined
         inline virtual rmat integral(
                             ^
installing to /home/mort_amini/splines2/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
ERROR: loading failed
* removing â€ک/home/mort_amini/splines2â€™

I would be grateful if you kindly let me know what might be the problem. 

Thanks

**Comment by wenjie2wang** [comment]
I do not have much clue.  But could you try to remove the `00LOCK` or `00LOCK-splines2` directory under `.libPaths()` and install the package without the `--no-lock` flag?

**Comment by wenjie2wang** [comment]
Close this issue due to inactivity.
