### ISSUE TITLE
Functions of splines2::mSpline do not sum to for periodic = TRUE and non-equidistant knots

### ISSUE THREAD

**Issue by BerriJ** [wenjie2wang/splines2#19]
Hi @wenjie2wang,

Sorry to bother you again concerning `splines2::mSpline`. I noticed that the spline functions do not sum to 1 if `periodic = TRUE` and non-equidistant knots are used. Consider the following reprex:

```
# install.packages("pbs")
# install.packages("splines2")

x <- 0:1000 / 1000
order <- 2
deg <- order - 1

knots <- c(0.00, 0.082, 0.23, 0.47, 1.00)

par(mfrow = c(1,2))

ts.plot(
    pbs::pbs(x,
        # pbs add boundary knots automatically
        knots = knots[c(-1, -5)],
        degree = deg, intercept = TRUE
    ),
    col = seq_along(knots),
    lwd = 2
)

ts.plot(
    splines2::mSpline(x,
        knots = knots[c(-1, -5)],
        degree = deg,
        Boundary.knots = c(0, 1),
        periodic = TRUE,
        intercept = TRUE
    ),
    col = seq_along(knots),
    lwd = 2
)
```

![plot](https://user-images.githubusercontent.com/37799358/228022146-28d3724c-36b6-490e-bab9-47c9bca2a56e.png)

Do you know if this is the supposed behavior? For my application, I need the functions to sum to one. 

Thank you very much. 
Best, BerriJ

**Comment by wenjie2wang** [comment]
> Do you know if this is the supposed behavior?

Yes, it is expected behavior for M-spline basis functions regardless of the argument `periodic`, which is the essential difference between B-spline and M-spline basis functions. The M-spline basis functions are normalized so that their integrals are one.  Consider the following example:

``` r
library(splines2)

x <- 0:1000 / 1000
order <- 2
deg <- order - 1
knots <- c(0.00, 0.082, 0.23, 0.47, 1.00)

res <- mSpline(
    x,
    knots = knots[c(-1, -5)],
    degree = deg,
    Boundary.knots = c(0, 1),
    periodic = TRUE,
    intercept = TRUE,
    integral = TRUE # check the integral
)
matplot(x, res, type = "l")
```

![](https://i.imgur.com/c9FXy3C.png)

<sup>Created on 2023-03-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by BerriJ** [comment]
Thank you for this insight. So, unfortunately, it's not possible to create periodic B-Splines using this package, right? Would you consider adding this functionality?

**Comment by BerriJ** [comment]
Thank you very much. I was unaware of (1), and it works fine (although one has to tweak the simple knot sequence a bit to reflect the periodicity). I'm busy now, but I'll add some code to this issue next week.

 I can also add a PR to integrate this into spline2 if you like. Ideas I came up with are:
- Adding a `periodic` argument to the bspline function
- As a method for the m-spline object for example `to_bspline()`

**Comment by wenjie2wang** [comment]
Glad to hear that (1) works!

Thank you for expressing interest in submitting a PR!  I have very similar ideas regarding this feature request.  We can construct periodic B-splines based on M-splines inside `bSpline()`.  However, it is just a quick workaround and can be inefficient.  In fact, it is straightforward to implement a `PeriodicBSpline` class in C++ following the existing `PeriodicMSpline` class.  I think it better to implement a template class for them.  A PR is welcome if you feel comfortable to implement the template class in C++.

**Comment by wenjie2wang** [comment]
Thanks for the reference code!  I will let you know after I implement the `PeriodicBSpline`, which should be straightforward enough without the need of scaling.

**Comment by wenjie2wang** [comment]
I added `periodicBSpline` mainly in this commit for your reference: https://github.com/wenjie2wang/splines2/commit/f27b4ed715957bc62615f96ada6c6676c8172bc6.
