### ISSUE TITLE
Natural cubic splines

### ISSUE THREAD

**Issue by fgoerlich** [wenjie2wang/splines2#3]
Is there in `splines2` a function to calculate natural cubic splines, like the `ns()` function in `splines`?
I haven´t found it.
Thanks,

**Comment by wenjie2wang** [comment]
No, the function that constructs natural cubic splines is currently not available in the **splines2** package.

**Comment by wenjie2wang** [comment]
@fgoerlich, the **splines2** v0.4.1 is available on CRAN. The function `splines2::naturalSpline()` provides an implementation of natural cubic splines that may be of your interest.
